export const serverBoardObj1 = {
  listInfo: [
    {
      id: 31,
      title: "음악 좋다",
      author: "codemodel6",
      date: "2024-05-21",
      contents: "노래 선정 기준 좋다아",
      like: 10,
    },
    {
      id: 30,
      title: "그림판..",
      author: "codemodel6",
      date: "2024-05-20",
      contents: "저장 배경화면이 없어서 좋다..",
      like: 0,
    },
    {
      id: 29,
      title: "잘 썼습니다",
      author: "asdhg21",
      date: "2024-05-19",
      contents: "글 좋네요",
      like: 1,
    },
    {
      id: 28,
      title: "주간게시판",
      author: "htthth11",
      date: "2024-05-19",
      contents: "주간게시판 겟또다제",
      like: 1,
    },
    {
      id: 27,
      title: "넷플릭스",
      author: "하이요",
      date: "2024-05-19",
      contents: "진짜 영화같다",
      like: 1,
    },
    {
      id: 26,
      title: "제목",
      author: "낭만검객",
      date: "2024-05-18",
      contents: "콘텐츠 입니다",
      like: 1,
    },
    {
      id: 25,
      title: "제목",
      author: "방문자",
      date: "2024-05-18",
      contents: "콘텐츠 입니다",
      like: 1,
    },
    {
      id: 24,
      title: "헐 밑에",
      author: "제드",
      date: "2024-05-18",
      contents: "야스오 뭐임 ㅎ;;",
      like: 1,
    },
    {
      id: 23,
      title: "등장",
      author: "야스오",
      date: "2024-05-17",
      contents: "바람이여.",
      like: 1,
    },
    {
      id: 22,
      title: "이번엔 뭐 하는게 좋을까요",
      author: "qwer",
      date: "2024-05-16",
      contents: "많이 써봄요 ㅎ;",
      like: 12,
    },
    {
      id: 21,
      title: "음악 좋다",
      author: "codemodel6",
      date: "2024-05-14",
      contents: "노래 선정 기준 좋다아",
      like: 10,
    },
    {
      id: 20,
      title: "호이호이",
      author: "도로로",
      date: "2024-05-13",
      contents: "반갑소",
      like: 0,
    },
    {
      id: 19,
      title: "방가루",
      author: "awww",
      date: "2024-05-11",
      contents: "wwww",
      like: 1,
    },
    {
      id: 18,
      title: "힝구",
      author: "울보",
      date: "2024-05-08",
      contents: "ㅠㅅㅜ",
      like: 1,
    },
    {
      id: 17,
      title: "우하하",
      author: "케로로",
      date: "2024-05-07",
      contents: "케로로중사",
      like: 1,
    },
  ],
  pageInfo: {
    page: 1,
    totalPage: 10,
  },
};

export const serverBoardObj2 = {
  listInfo: [
    {
      id: 5,
      title: "흠냐",
      author: "흠냐몬",
      date: "2024-04-21",
      contents: "흠냐",
      like: 10,
    },
    {
      id: 4,
      title: "자두자두졸랴",
      author: "자두",
      date: "2024-04-20",
      contents: "졸랴요..",
      like: 14,
    },
    {
      id: 3,
      title: "잘 썼습니다",
      author: "asdhg21",
      date: "2024-04-19",
      contents: "글 좋네요",
      like: 1,
    },
    {
      id: 2,
      title: "게시판",
      author: "htthth11",
      date: "2024-04-19",
      contents: "기능 신기하다",
      like: 1,
    },
    {
      id: 1,
      title: "첫 게시글",
      author: "하이요",
      date: "2024-04-19",
      contents: "작성완료",
      like: 1,
    },
  ],
  pageInfo: {
    page: 2,
    totalPage: 10,
  },
};
