export const topicList = [
  {
    rank: 1,
    title: "음악 좋다",
    author: "codemodel6",
    date: "2024-05-21",
    contents: "노래 선정 기준 좋다아",
    like: 10,
  },
  {
    rank: 2,
    title: "그림판..",
    author: "그림쟁이",
    date: "2024-05-20",
    contents: "저장 배경화면이 없어서 좋다..",
    like: 0,
  },
  {
    rank: 3,
    title: "잘 썼습니다",
    author: "asdhg21",
    date: "2024-05-19",
    contents: "글 좋네요",
    like: 1,
  },
  {
    rank: 4,
    title: "주간게시판",
    author: "htthth11",
    date: "2024-05-19",
    contents: "주간게시판 잘 썼습니다!",
    like: 1,
  },
  {
    rank: 5,
    title: "넷플릭스",
    author: "하이요",
    date: "2024-05-19",
    contents: "진짜 영화같다",
  },
];
